#!/bin/bash

#-------------------------------#
# SET PATH TO DIRECTORY
WORKDIR=$HOME/source_code/countMatrixFactor
#-------------------------------#

## delete *.o files if exists (generated by sourceCpp)
find $WORKDIR/pkg -type f -name "*.o" | xargs -I {} rm {}

## delete *.so files if exists (generated by sourceCpp)
find $WORKDIR/pkg -type f -name "*.so" | xargs -I {} rm {}

## compile attributes
Rscript --verbose $WORKDIR/admin/compileAttributes.R $WORKDIR

## compute MD5 sum
Rscript --verbose $WORKDIR/admin/computeMD5sum.R $WORKDIR

## build package
R CMD build $WORKDIR/pkg

## cp to src
ls *.tar.gz | xargs -I {} cp {} $WORKDIR/sources
