#!/bin/bash

#-------------------------------#
# SET PATH TO DIRECTORY
WORKDIR=$(git rev-parse --show-toplevel)
#-------------------------------#

## delete *.o files if exists (generated by sourceCpp)
find $WORKDIR/pkg -type f -name "*.o" | xargs -I {} rm {}

## delete *.so files if exists (generated by sourceCpp)
find $WORKDIR/pkg -type f -name "*.so" | xargs -I {} rm {}

## update version
VERSION=$(cat $WORKDIR/Version)
sed -i -e "s/Version:.*/Version: $VERSION/" $WORKDIR/pkg/DESCRIPTION

## compile attributes
Rscript --verbose $WORKDIR/admin/compileAttributes.R $WORKDIR

## generate doc
R -e "setwd(\"$WORKDIR/pkg\");library(roxygen2);roxygenize(\".\", roclets=c(\"rd\", \"collate\", \"namespace\"))"

## compute MD5 sum
Rscript --verbose $WORKDIR/admin/computeMD5sum.R $WORKDIR

## build package
R CMD build $WORKDIR/pkg

## cp to src
cp $WORKDIR/admin/pCMF_${VERSION}.tar.gz $WORKDIR/sources

## cp source to pbil-deb
#ls *.tar.gz | xargs -I {} scp {} durif@pbil:/panhome/durif/source_code/pCMF/sources
